name: push_master_ci

on:
  push:
    branches: [ master ]

jobs:
  build_and_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  docker_build_and_push:
    needs: [build_and_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file FamilyBudget/Dockerfile --tag yudakov1814/family_budget:${GITHUB_REF:11}
      - name: Push the Docker image
        run: docker push yudakov1814/family_budget:${GITHUB_REF:11}
